
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS languages;
DROP TABLE IF EXISTS publishers;
DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS subjects;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS ratings;

---------------------------------
--      Project Final DDL
---------------------------------

-- Start : extracted from isbndb_2022_09.jsonl

CREATE TABLE books (
    isbn                 text PRIMARY KEY,
    isbn13               text,
    title                text,
    title_long           text,
    authors              text[],        -- FK todo:  remove array
    subjects             text[],        -- FK todo:  remove array
    language             text,          -- FK todo:  remove array
    publisher            text,          -- FK todo:  remove array
    pages                integer,
    msrp                 numeric,
    binding              text,
    edition              text,
    image                text,
    dimensions           text,
    related              jsonb,
    synopsis             text,
    date_published_text  text,
    date_published       date
);

CREATE TABLE languages (
    code char(2) PRIMARY KEY,
    name character varying(20) NOT NULL
);

CREATE TABLE publishers (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    name character varying(50) UNIQUE NOT NULL
);

CREATE TABLE authors (
    id int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) UNIQUE NOT NULL
);

CREATE TABLE subjects (
    subject_id bigserial PRIMARY KEY,
    name character varying(50) UNIQUE NOT NULL,
    scheme character varying(50)
);

-- End : extracted from isbndb_2022_09.jsonl

-- Start : extracted from Kaggle DataSet

CREATE TABLE users (
    user_id INT PRIMARY KEY,
    Location VARCHAR(250),
    Age INT
);

CREATE TABLE ratings (
    user_id INT,
    ISBN VARCHAR(45),
    Book_rating SMALLINT,
    PRIMARY KEY (user_id, ISBN),
    FOREIGN KEY (user_id) REFERENCES Users(user_id)
);

-- End : extracted from Kaggle DataSet


